### ISSUE TITLE
3.8.2 compatibility with pretty table

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cmsd#8]
Bug: in 3.8.2 prettytable
Looks liek we got a new bug verified by the TA. We  believe that the bug did not occur on earlier versions of python. Something has changed in python so this bug occurs. The TA is looking at it.

 

Bug  in python 3.8.2 and pip 20.0.2 

Python versions 
"
root@dell-163-6:/cm# python --version; pip --version 
Python 3.8.2
pip 20.0.2 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
"
Error stack: 
"
(ENV3) niranda@dell-163-6:/aux/github/cm/cloudmesh-cmsd$ cmsd init 
MongoDB is on "running" mode!
Set key
Config Security Initialization

ERROR: executing command 'sec load'
======================================================================
max() arg is an empty sequence
max() arg is an empty sequence
Traceback (most recent call last):
  File "/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 1088, in main
    stop = cmd.onecmd(command)
  File "/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 360, in onecmd
    return func(arg)
  File "/cm/cloudmesh-cmd5/cloudmesh/shell/command.py", line 103, in new
    func(instance, args, arguments)
  File "/cm/cloudmesh-cloud/cloudmesh/sec/command/sec.py", line 169, in do_sec
    list_all()
  File "/cm/cloudmesh-cloud/cloudmesh/sec/command/sec.py", line 161, in list_all
    Print("all", data)
  File "/cm/cloudmesh-cloud/cloudmesh/sec/command/sec.py", line 138, in Print
    print(Printer.write(liste,
  File "/cm/cloudmesh-common/cloudmesh/common/prettytable.py", line 233, in __str__
    return self.__unicode__()
  File "/cm/cloudmesh-common/cloudmesh/common/prettytable.py", line 239, in __unicode__
    return self.get_string()
  File "/cm/cloudmesh-common/cloudmesh/common/prettytable.py", line 977, in get_string
    self._compute_widths(formatted_rows, options)
  File "/cm/cloudmesh-common/cloudmesh/common/prettytable.py", line 889, in _compute_widths
    widths[index] = max(widths[index], min(_get_size(value)[0], self.max_width[fieldname]))
  File "/cm/cloudmesh-common/cloudmesh/common/prettytable.py", line 80, in _get_size
    width = max([_str_block_width(line) for line in lines])
ValueError: max() arg is an empty sequence

======================================================================

Variables

    trace=False
    debug=False
    group=cloudmesh
    experiment=base
    cloud=chameleon
    cluster=clustera
    timer=False
    key=aaaa
"

**Comment by laszewsk** [comment]
must be fixed as cloudmesh must be compatible with 3.8.2

**Comment by laszewsk** [comment]
a fix was committed
